"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {encodeHeader}=require("../../packages/x402/payment");
const {AMOUNT_ATOMIC,PRICE,RESOURCE_PATH,productPaymentDocument,createPaidTreasuryThresholdHandler}=require("./paid-handler");
function response(body,status=200){return{status,ok:status>=200&&status<300,async json(){return body;}};}
const sig=()=>encodeHeader({x402Version:2,payload:{signed:true}});
test("Product 007 terms are $0.003 / 3000 atomic",()=>{const d=productPaymentDocument("https://example.test");assert.equal(PRICE,"$0.003");assert.equal(AMOUNT_ATOMIC,"3000");assert.equal(d.resource.url,"https://example.test"+RESOURCE_PATH);});
test("unpaid returns 402 without source work",async()=>{let c=0;const h=createPaidTreasuryThresholdHandler({publicApiBase:"https://example.test",service:{async check(){c++;}},fetchImpl:async()=>response({})});const r=await h({query:{security:"Total Marketable",thresholdPercent:"4"},event:{headers:{}}});assert.equal(r.statusCode,402);assert.equal(c,0);});
test("valid payment verifies then settles after result",async()=>{const urls=[];const h=createPaidTreasuryThresholdHandler({publicApiBase:"https://example.test",service:{async check(){return{decision:"threshold_met",sourceFailures:[],chargeable:true};}},fetchImpl:async url=>{urls.push(url);return url.endsWith("/verify")?response({isValid:true}):response({success:true,transaction:"0x007"});}});const r=await h({query:{security:"Total Marketable",thresholdPercent:"4"},event:{headers:{"payment-signature":sig()}}});assert.equal(r.statusCode,200);assert.deepEqual(urls.map(x=>x.split("/").pop()),["verify","settle"]);});
test("Treasury source failure does not settle",async()=>{const urls=[];const h=createPaidTreasuryThresholdHandler({publicApiBase:"https://example.test",service:{async check(){return{decision:"human_review",sourceFailures:[{source:"treasury_fiscal_data",detail:"down"}],chargeable:false};}},fetchImpl:async url=>{urls.push(url);return response({isValid:true});}});const r=await h({query:{security:"Total Marketable",thresholdPercent:"4"},event:{headers:{"payment-signature":sig()}}});assert.equal(r.statusCode,502);assert.equal(urls.length,1);});
